POST http://localhost:8080/api/v1/auth/signup
Content-Type: application/json
Accept-Language: en

{
    "username": "kcramakr1",
    "password": "test1234",
    "fullName": "Kumaresh C R",
    "mobileNo": "9164274561",
    "email": "crk12@test.com",
    "dob": "2023-12-24"
}

###

http://localhost:8080/api/v1/auth/signup/exists/username?username=kcramakr

###

http://localhost:8080/api/v1/auth/signup/exists/email?email=crk@test.com

###

http://localhost:8080/api/v1/auth/signup/exists/mobileno?mobileno=9164274560

###

POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json
Accept-Language: en

{
    "strategy": "EMAIL_PASSWORD",
    "username": "crk2@test.com",
    "password": "test1234"
}

###

GET http://localhost:8080/api/v1/auth/validate/token
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJrY3JhbWFrciIsImlhdCI6MTcxNzc4MTQ4MCwiZXhwIjoxNzE3Nzg1MDgwfQ.JlRMefcT9EU_pHb3CWu8XtRvkC7sidiRsdfGCZVKXvw


###
